### PR TITLE
Update admin.py compatibility with Django 1.6

### PR DESCRIPTION
**Pull request by javiercf**
removed defaults parameter in get_urls method that crashes the SingletonModelAdmin Class

### CODE REVIEW

**Comment by defbyte** [comment]
Hi @javiercf , thanks for submitting the pull request!

We need to make sure we maintain backwards compatibility, as there are a few legacy projects that use this package which are stuck on older version of Django (one of which is on Django 1.3.x).

Perhaps with a simple `ImportError` check?

**Comment by javiercf** [comment]
hey @defbyte you're totally right, I just added the `ImportError` check, hope it helps!

**Comment by defbyte** [comment]
@javiercf  I'll need to update the version number, repackage, and upload to PyPi

**Comment by defbyte** [comment]
Release created and PyPi updated: https://pypi.python.org/pypi/django-singleton/0.1.9

**Pull request merged**
